name: quizzler
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^5.1.0
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/